// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iigydvobwdeczocmrlio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpZ3lkdm9id2RlY3pvY21ybGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MTgyNTcsImV4cCI6MjA1NTk5NDI1N30.tzTLCMSBX1kcXzOIPPPbNnhQrg8ROT01FGodalwFc_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);